#!/bin/sh

# Set these paths appropriately

BIN="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/treetagger/bin"
CMD="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/treetagger/cmd"
LIB="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
