#!/bin/sh

# Set these paths appropriately

BIN="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/bin"
CMD="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/cmd"
LIB="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations
PARFILE=${LIB}/finnish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

