#!/bin/sh

# Set these paths appropriately

BIN="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/bin"
CMD="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/cmd"
LIB="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
