#!/bin/sh

# Set these paths appropriately

BIN="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/bin"
CMD="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/cmd"
LIB="/Users/cabelotaina/apps/web-mining/parte-3-proyecto-3/src/tagger-scripts/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
